### PR TITLE
add PDF standards from Adobe open-source page

### PR DESCRIPTION
**Pull request by adehad**
I was really struggling to find working links to the PDF standard reference.

It looks like Adobe has made these open-source since 2008 for the sake "to make, use, sell, and distribute PDF-compliant implementations." https://en.wikipedia.org/wiki/PDF#cite_note-8

Which we all basically fall under.

It would be great if we can store these here and then perhaps reference them in the PyPDF2 repo of where to look for understanding how the standard works for a feature contribution !
I myself am looking to make a contribution and hopefully will be able to wrap my head around the reference to be able to do so.

### CODE REVIEW

**Comment by MartinThoma** [comment]
I'm very hesitant to add files to this repository. I see the benefit, but I would very much prefer links

I need to think about this.

I guess we don't have lawyers here ... but what do others think about adding the files?

@MasterOdin , do you happen to have an opinion on this PR?

**Comment by MasterOdin** [comment]
> It looks like Adobe has made these open-source since 2008 for the sake "to make, use, sell, and distribute PDF-compliant implementations." [en.wikipedia.org/wiki/PDF#cite_note-8](https://en.wikipedia.org/wiki/PDF#cite_note-8)

The key word here is _implementations_, where it's allowed to freely distribute pyPDF2 as Adobe won't try to push copyright claims against it. It's not that it makes it free to distribute the PDF specification, especially given that ISO happily charges you ~$200 to get it from them (https://www.iso.org/standard/51502.html).

Additionally, per the second page of the 1.7 PDF from Adobe:

> This document has been derived directly from the copyright ISO 32000-1 standard document available for purchase from the ISO web site at http://www.iso.org/iso/iso_catalogue/catalogue_tc/catalogue_detail.htm?csnumber=51502. It is being made available from the web site of Adobe Systems Incorporated (http://www.adobe.com/devnet/pdf/pdf_reference.html) under agreement with ISO for those that do not need the official version containing the ISO logo and copyright notices. This version of the ISO 32000-1 standard is copyright by Adobe Systems Incorporated through an agreement with ISO who is the copyright owner of the official ISO 32000-1 document of which this is an authorized copy.

The language here would read to me that it's only authorized to get this PDF directly from Adobe, and otherwise we would trend into the realm of making unauthorized copies. My vote would be that you modify the README to just link to the 1.7 page (and maybe mention it's on Adobe's site), and not include it into this repo, unless you want to go through the legwork of getting approval from Adobe/ISO to redistribute.

**Comment by adehad** [comment]
Thanks for explaining that thought process!

I've changed them to links

**Comment by MartinThoma** [comment]
Thank you @adehad :heart:

**Pull request merged**
